### ISSUE TITLE
[HELP WANTED] Can't upgrade Jetty without breaking WebSocket implementation

### ISSUE THREAD

**Issue by tipsy** [perwendel/spark#827]
Upgrading breaks the tests, but that can be fixed as seen in #698.
This only fixes the tests though. When actually trying to run a project which uses WebSockets, I get:

```
Exception in thread "Thread-0" java.lang.NoClassDefFoundError: org/eclipse/jetty/http/pathmap/PathSpec
	at spark.embeddedserver.jetty.EmbeddedJettyServer.ignite(EmbeddedJettyServer.java:108)
	at spark.Service.lambda$init$2(Service.java:504)
```

We need to update the implementation, and write some better tests.

**Comment by tipsy** [comment]
@joakime I don't suppose you have more time on your hands, and could look at this one too? I saw your name a lot while digging through the jetty source code.

**Comment by joakime** [comment]
Yeah, sure, no problem.
I wrote the websocket code afterall.
I'll have to help you get over the 9.4.5 hurdle in the future too. 
(Support for javax.websocket 1.1 changes were massive)

**Comment by tipsy** [comment]
@joakime Do you know when you'll get time to look at this? We want to release 2.6 soon, and we're wondering if this could make it into the release.

**Comment by joakime** [comment]
@tipsy see PR #838

**Comment by tipsy** [comment]
Thanks!
