### ISSUE TITLE
Spark 2.5 don't work with Jetty 9.4.0.M0

### ISSUE THREAD

**Issue by victorwss** [perwendel/spark#630]
Seems that Jetty 9.4.0 introduced an incompatible change that broken the EmbeddedJettyServer class. See my stacktrace:

`Exception in thread "Thread-1" java.lang.NoClassDefFoundError: org/eclipse/jetty/websocket/server/pathmap/PathSpec
    at spark.embeddedserver.jetty.EmbeddedJettyServer.ignite(EmbeddedJettyServer.java:105)
    at spark.Service.lambda$init$0(Service.java:349)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.websocket.server.pathmap.PathSpec
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 3 more`

This is the relevant part of my classpath:
- jetty-http-9.4.0.M0.jar
- jetty-io-9.4.0.M0.jar
- jetty-security-9.4.0.M0.jar
- jetty-server-9.4.0.M0.jar
- jetty-servlet-9.4.0.M0.jar
- jetty-util-9.4.0.M0.jar
- jetty-webapp-9.4.0.M0.jar
- jetty-xml-9.4.0.M0.jar
- websocket-api-9.4.0.M0.jar
- websocket-client-9.4.0.M0.jar
- websocket-common-9.4.0.M0.jar
- websocket-server-9.4.0.M0.jar
- websocket-servlet-9.4.0.M0.jar
- spark-core-2.5.jar
- slf4j-api-1.7.21.jar
- slf4j-simple-1.7.21.jar
- javax.servlet-api-4.0.0-b01.jar

It choked on the PathSpec interface that used to be present in websocket-server-9.3.6.v20151106.jar (and probably also in a few newer versions). Now I tried to move to Jetty 9.4.0.M0, and that interface is not there anymore because it was moved to the jetty-http-9.4.0.M0.jar file. However, the package name also changed from org.eclipse.jetty.websocket.server.pathmap to org.eclipse.jetty.http.pathmap.

Going to line 105 of the EmbeddedJettyServer, it is not something obvious for me that I could easily and readily fix.

This also rises me an alert. The guys from Jetty don't really care if they will break other people code by refactoring their codebase around (I already got a similar issue last year with another tool that ceased to work due to this exact reason, though with earlier Jetty versions). This means that anything which directly interact with Jetty classes is inherently brittle, including Spark.

So, to solve this and ensure that this won't happen again in the future, I think that the Jetty-dependent classes would need to be moved to a JAR of their own tied to both the Spark version and Jetty's version (let's call it spark-on-jetty-xxx.jar, where xxx is the version) . The upsides are:
- Whenever the Jetty guys introduce an incompatible change, just release a new spark-on-jetty package. No need to release a new full spark-core package.
- People who use something else instead of Jetty will get rid of the unused jetty-related classes from their Spark.
- This also open up the road for a future implementation of something like a spark-on-tomcat, spark-on-glassfish, spark-on-youknowwhat implementation.

The downside is the need to have still yet another JAR in the classpath.

**Comment by AN3Orik** [comment]
Are u serious? Month for fixing one import =\

**Comment by tipsy** [comment]
On vacation.

**Comment by DrVanScott** [comment]
Still on vacation?

**Comment by tipsy** [comment]
Nope.

**Comment by jakaarl** [comment]
Shameless plug: would PR #674 be of any help?

**Comment by Mona19** [comment]
We can use maven repository update feature in case there is some version change, in order to resolve such issues.

**Comment by topicscout** [comment]
I have hit the same problem. I really like SparkJava, and wanted to use to set up http resources, especially for test purposes. Unfortunately, I am getting the missing PathSpec error.

Exception in thread "Thread-1" java.lang.NoClassDefFoundError: org/eclipse/jetty/websocket/server/pathmap/PathSpec
	at spark.embeddedserver.jetty.EmbeddedJettyServer.ignite(EmbeddedJettyServer.java:106)
	at spark.Service.lambda$init$1(Service.java:391)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.websocket.server.pathmap.PathSpec
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 3 more

Seems to be the same problem reported so well by Victor.

**Comment by tipsy** [comment]
We will update jetty soon, don't really need an issue for this. Other points about splitting project up is also discussed elsewhere.
